apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-firebase-app
  labels:
    app: react-firebase-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-firebase-app
  template:
    metadata:
      labels:
        app: react-firebase-app
    spec:
      containers:
      - name: react-firebase-app
        image: saikiran078/react-firebase-cicd:replaceImageTag
        ports:
        - containerPort: 8080
